### ISSUE TITLE
CI not running on PRs?

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/ci#32]
Is our CI working properly for our Exchange packs?

I would have expected this PR here https://github.com/StackStorm-Exchange/stackstorm-vadc/pull/1 to show results of checks. Looks like checks aren't being run?

**Comment by emedvedev** [comment]
https://circleci.com/gh/StackStorm-Exchange/stackstorm-vadc/edit#advanced-settings
"Permissive building of pull requests" has to be enabled. We'll also need to enable it by default in the Bootstrap script, and retroactively enable for other repos.

**Comment by emedvedev** [comment]
Enabled for vadc, but I think the PR will have to be resubmitted for the checks to run
