### ISSUE TITLE
Slack webhooks not working for Exchange packs

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/ci#33]
We're seeing 500 responses with the Slack webhook integration for Exchange packs - e.g.: https://github.com/StackStorm-Exchange/stackstorm-vault/settings/hooks/10916336#delivery-response

Headers:
```
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 39
Content-Security-Policy: referrer no-referrer;
Content-Type: text/html
Date: Fri, 09 Dec 2016 13:55:41 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
Via: 1.1 9552af4ceb2e0dd55964a80d1e549fd5.cloudfront.net (CloudFront)
X-Amz-Cf-Id: HZX-n7VkLLdLErEvYjTlGi52GafxpT5bZUG6nq0knQ9V7PUs565VzQ==
X-Cache: Error from cloudfront
X-Frame-Options: SAMEORIGIN
X-Slack-Backend: h
```

Body:
```
missing_text_or_fallback_or_attachments
```

Looks like something not working properly?

Interestingly, in the request, we see this `content-type: application/x-www-form-urlencoded`

But in the webhook configuration, it says use `application/json`
Unclear why.

**Comment by LindsayHill** [comment]
Some incorrect web hook URLS used. Working through fixes.

**Comment by Kami** [comment]
We had this issue in the past - I fixed it by generating a new Slack webhook URL and update all the repos to use that?

@LindsayHill did it break again, or?

**Comment by LindsayHill** [comment]
@Kami It looks like a bunch of repos were set up with an older webhook URL that was revoked. Might have been some wrong credentials used somewhere. I did some ugly scripting to work through identifying them & cleaning them up. Should be OK now.

(Also looked like there might have been a fix applied that used a script that only worked on the first 100 repos, which is default number returned from GitHub API. Seemed to be more likely to have problems with the repos named stackstorm-x...., stackstorm-y..., stackstorm-z..., etc)

**Comment by LindsayHill** [comment]
I figured out why some of the repos weren't updated when you ran a script. Problem is here:

https://github.com/StackStorm-Exchange/ci/blob/master/tools/common.sh#L14

cf with https://developer.github.com/v3/#pagination
>  For some resources, you can also set a custom page size up to 100 with the ?per_page parameter

Doesn't matter if you ask for 1,000...GH API will only return the first 100. Will open separate issue for this

**Comment by Kami** [comment]
Good catch - I could have swore it worked at some point.

We encountered that issue in the past, I added this `?per_page=1000` as temporary work-around and it seemed to have worked.

In any case, looks like it's not working anymore so we need to go with actual "handle multiple pages" approach :)
