### ISSUE TITLE
Deployment step race condition

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/ci#65]
In https://github.com/StackStorm-Exchange/ci/blob/master/.circle/deployment#L23, the deployment script clones the github.com/StackStorm-Exchange/index repo, then updates `index.json` and the pack icon.png. 

It then commits & pushes those changes.

If multiple packs are attempting to deploy changes around the same time, this can result in a race where multiple packs are attempting to push to master at the same time. 

Code needs to be updated to handle this, and attempt to rebase with latest changes, and push again. Possibly with a few retries.

**Comment by cognifloyd** [comment]
This is obsolete now that index regeneration happens in the index repo itself.
