### ISSUE TITLE
Deployment step needs better failure logging

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/ci#66]
When pushing changes to the index repo, the push step sometimes fails due to a race condition, or other situations such as invalid access token.

This causes the deployment step to exit, but the logs are unhelpful, because the [code](https://github.com/StackStorm-Exchange/ci/blob/master/.circle/deployment#L61) contains this:

`git -C ~/index push origin 2>/dev/null`

It would be helpful to have better logging here to identify the cause of the failure. (as well as fix the race condition, see #65)

**Comment by cognifloyd** [comment]
Marking this as obsolete. When we identify future improvements, we should file new issues and specify which workflow to target (the pack test workflow, the index regen workflow, the pack bootstrap workflow, etc)
