### ISSUE TITLE
Release tagging for packs can leave out changes desired for a given release

### ISSUE THREAD

**Issue by nmaludy** [StackStorm-Exchange/ci#91]
Over the last several weeks we've noticed and had to correct several packs where the tagged release version did not include the changes that were merged with the PR.

Looking into this i believe i found the culprit: https://github.com/StackStorm-Exchange/ci/blob/master/.circle/deployment#L33-L52

This code is where we create release tags on the pack repos. If you notice we're pulling a revlist for `pack.yaml`. What is happening is that changes made to a PR that are committed AFTER a `pack.yaml` has been updated are being excluded from the release.

Example: https://github.com/StackStorm-Exchange/stackstorm-terraform/pull/26/commits

You can see there are three commits in this PR:
 - 1edf85c some code updates
 - 8fa2dab update to pack.yaml
 - 0313c69 merge from master -> this branch

Since 8fa2dab is the change that updated pack.yaml it is the one that got the 0.5.0 tag: https://github.com/StackStorm-Exchange/stackstorm-terraform/releases/tag/v0.5.0

This left out  0313c69 causing changes that were already merged into master from being excluded from the release.

A new release had to be cut in order to tag the latest commit.

**Comment by blag** [comment]
I think `git rev-list --tags $(git describe --tags --abbrev=0)` will get all of the commits since the last tag, which is probably what we want to do.

If I read that code right, with my changes, it will dig through all of the commits since the last tag, and create a tag locally (if it doesn't already exist) for every commit that touches `pack.yaml`, and push the tag back to GitHub (if it doesn't already exist there).

**Comment by nmaludy** [comment]
Brainstorming here...

Maybe what we really want is to find where branch `x` merges into `master` and take the latest `pack.yaml` version from `x` and tag the merge commit into `master` with this tag. 

Am i on the right path here?

**Comment by armab** [comment]
Good idea!

**Comment by nmaludy** [comment]
Going a little bit further, it thing from the code's perspective the psuedocode would look something like....

```
if repo.latest_commit is a merge commit AND repo.branch == 'master'
  check if pack.yaml version was changed on this branch
  tag repo.latest_commit with version from pack.yaml
end
```

Playing around with `git` on the command line looks like we can get the diff of `pack.yaml` from a merge commit using the following syntax:

```
export MERGE_COMMIT=2988e32f13abb63aefb6ee087a3a4f344e91b54c
$ git diff $MERGE_COMMIT^1 $MERGE_COMMIT -- pack.yaml
diff --git a/pack.yaml b/pack.yaml
index 17ec0a4..e346686 100755
--- a/pack.yaml
+++ b/pack.yaml
@@ -5,7 +5,7 @@ runner_type: "python-script"
 description: Terraform integrations
 keywords:
   - terraform
-version: 0.4.1
+version: 0.5.0
 author: Martez Reed
 email: martez.reed@greenreedtech.com
 python_versions:
```

To get just the version line diff we can do:
```
$ git diff $MERGE_COMMIT^1 $MERGE_COMMIT -- pack.yaml | grep -E '+version:'
+version: 0.5.0

$ git diff $MERGE_COMMIT^1 $MERGE_COMMIT -- pack.yaml | grep '+version:'; echo $?
+version: 0.5.0
0

# if grep fails it will return 1
```

So, we should be able to check if the version of `pack.yaml` was updated during the merge commit  and then use the current means to read the current pack version and tag it.

Thoughts?

**Comment by armab** [comment]
Sounds like a plan :+1:

**Comment by cognifloyd** [comment]
This was resolved with the move to Github Actions
