### ISSUE TITLE
Broken Makefile

### ISSUE THREAD

**Issue by seddarj** [StackStorm-Exchange/ci#96]
Hello,

It seems that since commits like [this one](https://github.com/StackStorm-Exchange/ci/commit/123788487ec4ffc6a92d7e18cf1d60aa29035d1e#diff-c55708b06365adc163e9d3daad0f325c) were pushed around August 5th, the CI has been broken.

It fails during the `flake8` step with the following error:
```
Force flake8 checks on all files
Makefile:102: *** Recursive variable 'PYTHONPATH' references itself (eventually).  Stop.

Exited with code exit status 2
```

I first noticed it breaking today while working on a new feature branch so I relaunched on old CircleCI pipeline that was working on August 3rd and it failed with the same error.

**Comment by nmaludy** [comment]
@punkrokk can you take a look here?

**Comment by punkrokk** [comment]
Can I get an example of a failed build job?

**Comment by seddarj** [comment]
Sure @punkrokk, what exactly do you need?

Also, looking at the output it seems there's an issue with this [line](https://github.com/StackStorm-Exchange/ci/blob/master/.circle/test#L42) in `.circle/test`. I've submitted a PR [here](https://github.com/StackStorm-Exchange/ci/pull/97) to fix that one.

**Comment by seddarj** [comment]
```
#!/bin/bash -eo pipefail
~/ci/.circle/test
Running on branch: ***
Running with Python from /home/circleci/virtualenv/bin/python
Python version: Python 3.6.12
/home/circleci/ci/.circle/test: line 42: : command not found
ROOT_DIR=
FORCE_CHECK_ALL_FILES=
======================= compile ========================
------- Compile all .py files (syntax check test) ------
if python -c 'import compileall,re; compileall.compile_dir(".", rx=re.compile(r"/virtualenv|virtualenv-osx|virtualenv-py3|.tox|.git|.venv-st2devbox"), quiet=True)' | grep .; then exit 1; else exit 0; fi

All files compiled successfully

==================== license-check ====================

Pack is licensed under the Apache 2.0 License -- :)

==================== flake8 ====================

. ~/virtualenv/bin/activate; \
if [ "${FORCE_CHECK_ALL_FILES}" = "true" ]; then \
	echo "Force flake8 checks on all files"; \
	find /home/circleci/repo/* -name "*.py" | while read py_file; do \
		flake8 --config=/home/circleci/ci/lint-configs/python/.flake8 $py_file || exit 1; \
	done; \
elif [ 1 -gt 0 ]; then \
	echo "Checking 1 Python files"; \
	/home/circleci/ci/utils/git-changes py >~/.git-changes-py; \
	while read -r file; do \
		if [ -n "$file" ]; then \
			flake8 --config=/home/circleci/ci/lint-configs/python/.flake8 $file || exit 1; \
		fi; \
	done < ~/.git-changes-py; \
	if [ -e ~/.git-changes-py ]; then rm ~/.git-changes-py; fi; \
else \
	echo "No files have changed, skipping run..."; \
fi;
Checking 1 Python files
Makefile:102: *** Recursive variable 'PYTHONPATH' references itself (eventually).  Stop.

Exited with code exit status 2
CircleCI received exit code 2
```

Even after manually fixing line 42 of `.circle/test`, I get the same issue regarding the `PYTHONPATH`

**Comment by seddarj** [comment]
Ok, I've closed my PR after reading the recent additions around `COMMON_LIBS`. I guess we don't set the variable and that's why we're having issues.

I'm going to try again by setting the variable, will let you know.

**Comment by punkrokk** [comment]
@seddarj Thanks. So - you should set it to blank, unless you are trying to test things that use the COMMON_LIBS path. 

I can't tell how you are running the test script, so there is that, but if COMMON_LIBS is not set, we should just evaluate the else after line 42.

**Comment by seddarj** [comment]
Setting the variable fixes the issue at line 42 but doesn't fix the Makefile issue. Exact same error:
```
#!/bin/bash -eo pipefail
~/ci/.circle/test
Running on branch: ***
Running with Python from /home/circleci/virtualenv/bin/python
Python version: Python 3.6.12
ROOT_DIR=
FORCE_CHECK_ALL_FILES=
======================= compile ========================
------- Compile all .py files (syntax check test) ------
if python -c 'import compileall,re; compileall.compile_dir(".", rx=re.compile(r"/virtualenv|virtualenv-osx|virtualenv-py3|.tox|.git|.venv-st2devbox"), quiet=True)' | grep .; then exit 1; else exit 0; fi

All files compiled successfully

==================== license-check ====================

Pack is licensed under the Apache 2.0 License -- :)

==================== flake8 ====================

. ~/virtualenv/bin/activate; \
if [ "${FORCE_CHECK_ALL_FILES}" = "true" ]; then \
	echo "Force flake8 checks on all files"; \
	find /home/circleci/repo/* -name "*.py" | while read py_file; do \
		flake8 --config=/home/circleci/ci/lint-configs/python/.flake8 $py_file || exit 1; \
	done; \
elif [ 1 -gt 0 ]; then \
	echo "Checking 1 Python files"; \
	/home/circleci/ci/utils/git-changes py >~/.git-changes-py; \
	while read -r file; do \
		if [ -n "$file" ]; then \
			flake8 --config=/home/circleci/ci/lint-configs/python/.flake8 $file || exit 1; \
		fi; \
	done < ~/.git-changes-py; \
	if [ -e ~/.git-changes-py ]; then rm ~/.git-changes-py; fi; \
else \
	echo "No files have changed, skipping run..."; \
fi;
Checking 1 Python files
Makefile:102: *** Recursive variable 'PYTHONPATH' references itself (eventually).  Stop.

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by seddarj** [comment]
Setting `COMMON_LIBS="true"` doesn't change much either. I get the same issue with an extra `Common libs PATH selected` at the beginning corresponding to what happens in `.circle/test` line 42

**Comment by seddarj** [comment]
Hello @punkrokk, turns out we had `PYTHONPATH: "/home/circleci/repo/lib:${PYTHONPATH}"` set in our CircleCI environment variables definition which was conflicting with the `export PYTHONPATH=/home/circleci/repo/lib:${PYTHONPATH}` found in the Makefile.

Removing the variable in CircleCI and setting `COMMON_LIBS` to `true` solved the issue for us.

Thanks for looking into this.
